### ISSUE TITLE
XSS proof authorName

### ISSUE THREAD

**Issue by galadhremmin** [galadhremmin/Parf-Edhellen#11]

**Comment by galadhremmin** [comment]
Fixed.

**Comment by TPS** [comment]
@galadhremmin Is this fixed?  Or did something come up to show that it isn't?

**Comment by galadhremmin** [comment]
@TPS I believe the XSS proofing code is a bit too naïve in its current form. It needs to be reworked, and I believe this is why I reopened the issue. As I've been working on my own for years on ElfDict, I've admittedly not been too concerned with using this tool as a bug tracker. I apologise for the ambiguity!
