### ISSUE TITLE
Move site away from StartSSL certificate

### ISSUE THREAD

**Issue by TPS** [galadhremmin/Parf-Edhellen#13]
@galadhremmin In preparation for [Mozilla's reported proposed removal of WoSign & StartSSL](https://www.google.com/search?q=wosign+startssl), I disabled those roots in my browser.  When I re-opened [Parf Edhellen](https://www.elfdict.com/), it turns out that you use StartSSL!

Maybe you want to migrate to [Let's Encrypt](https://letsencrypt.org/) or something more reputable?

**Comment by galadhremmin** [comment]
Hi @TPS! Thank you for informing me about this issue. I just learned about this myself today through the podcast Security Now. I will be looking into changing the certificate next week.

**Comment by galadhremmin** [comment]
ElfDict's host doesn't seem to support Let's Encrypt. I've sent a message to my host, asking if it's possible to implement this in the future. I can't manually generate certificates for ElfDict as their life time is only 90 days.

**Comment by TPS** [comment]
It turns out that you _may_ not have to, because of updates in the last ~48 hours.…  I'm sure SG will be covering it soon, but the latest is that StartSSL is reorganizing under different ownership in hopes of saving the brand.  _Iff_ the implemented changes are acceptable to the security community (a ___HUGE___ iff), they'll invalidate all old certs & reissue new 1s under the new secure architecture.  For now, it _may_ be sufficient for you just to drop the cert/HSTS & go HTTP for a little bit, while waiting for a new cert.

**Comment by TPS** [comment]
Also, does something like [Netlify](https://github.com/isaacs/github/issues/156#issuecomment-243328658) work for you?

**Comment by galadhremmin** [comment]
My host is working with Symantic to implement a similar solution (https://www.symantec.com/theme/encryption-everywhere) but it won't be ready until next year. So in light of this, I've generated a 90-day certificate using Let's Encrypt, and working on convincing my host to install it for my site. The discussions are still ongoing.

**Comment by galadhremmin** [comment]
I've fixed it by transitioning to Amazon Lightsail! Thank you for the feedback @TPS !

**Comment by TPS** [comment]
@galadhremmin Fantastic result on [SSLTest](https://dev.ssllabs.com/ssltest/analyze.html?d=elfdict.com), too, other than a currently-minor quibble about [__DNS CAA:	No__](https://community.qualys.com/thread/16967-configure-dns-caa), which you'd hafta take up w/ Lightsail, if you choose.

Congrats!

**Comment by galadhremmin** [comment]
@TPS I reached out to FSData which still manages my domain names, and their DNS unfortunately does not support this feature yet. I'll see what I can do.
