### ISSUE TITLE
How to Contribute?

### ISSUE THREAD

**Issue by ghost** [galadhremmin/Parf-Edhellen#32]
Hello @galadhremmin,

I am interested in contributing and am wondering what someone could do to support Parf Edhellen on the development side.

What are the contribution guidelines?  Are there any recent bugs?  A new feature to develop?  Any part of v71 needing attention?

I would suggest adding a license and potentially expanding Parf Edhellen's interface into other languages.  I can translate Korean.

Thanks,
Calrethil

**Comment by galadhremmin** [comment]
Mae govannen Calrethil!

Thank you so much for your interest in the _Parf Edhellen_ and your super generous offer of wanting to help out! This would open up so many new ways to improve the website and deliver new features and correct long-standing bugs.

This project is 10 years old, and I frankly gave up hope finding someone else who would be interested in the project more than a few years ago. For this reason, I have not thought of contribution guidelines and I have not been thorough in employing the built-in bug tracking and bug remediation tools offered by Github. The documentation is also "a little" out of date, as Parf Edhellen's current version is 431. :)

I'll do better by bringing the documentation up to date in the coming weeks. Do you have any preferences with respect to the contribution guidelines? Any prior art you'd like me to draw inspiration from?

Regarding bugs and feature requests, there are plenty. I'll see what I can do to curate a list of them. One major bug that comes to mind is the 500 Server Error when you open a contribution in the old data format. Contributions pending review are serialized and stored in JSON format in the _contributions_ table. The contribution format has evolved a lot over the years, and the most recent change was a breaking change. I did not migrate previous, pending contributions nor did I retain support for them in the service, which has unfortunately led to a crash when clients try to open them. This is something I'd like to fix. I'll see what I can do to register a formal bug with a stack trace.

If there is any information you need to get the service up and running on your machine, let me know! I'll try my best to help you out! :)

Cheers,
Aldaleon

**Comment by CalrethilOfMirkwood** [comment]
Mae govannen Aldaleon!

Thanks for getting back to me!  I'm exited to work on such an interesting project.

I'd prefer that I have my own fork where I can push changes.

I do not have any other preferences for contribution guidelines.  However, I'd like to work with a kanban-style project board for organizing tasks as I have found it useful in the past.

I'll look into the compatibility error you mentioned and see what I can do about it.

Thanks,
Calrethil

**Comment by IanoNjuguna** [comment]
Hey @galadhremmin && @CalrethonOfMirkwood 
I'd like to help out by adding a contributor's code of conduct. Is it okay if I did so?

**Comment by CalrethonOfMirkwood** [comment]
Embarrassingly I haven't actually done anything for parf-edhellen (largely because I have no Idea what I should be doing).  So yes, that would be very helpful for me!  But I'd wait for approval from @galadhremmin before doing anything yet since he's running the project.

**Comment by galadhremmin** [comment]
Hi! Thank you for your interest - I'd love some support! 😀 I do apologise, though - I've been so preoccupied with work and home renovations that I haven't had much time for anything else lately. 

@IanoNjuguna You're very welcome to do so! I'm curious, are you going to base it off some kind of template? Or should we iterate on it together?

@CalrethonOfMirkwood I remember you were requesting a backlog of sorts for the project. I'm currently abroad on a business trip, but when I get back home this weekend, I'll look into creating a board of various tasks.

**Comment by IanoNjuguna** [comment]
@galadhremmin I'll use a template as the base and the iterations to modify it so that it suits us better.

**Comment by galadhremmin** [comment]
All right, so I'm back from my trip now!

> I'll use a template as the base and the iterations to modify it so that it suits us better.
Go ahead! This is a great idea and something that we really should have already. Thank you!

> Also interested in a to-do list... github's internal "projects" tab might be a simple way to start that and have it handy for interested contributors!
I think it'd be great to keep things within Github. I'll do some research tonight on what is needed to get going.

**Comment by galadhremmin** [comment]
I've created a bunch of tasks of things that are on top of my mind. It's not comprehensive but it should at least give a directional impression of what I'm worrying about or would like to invest time building.
