### ISSUE TITLE
Deleting account on website

### ISSUE THREAD

**Issue by tabi-cat** [galadhremmin/Parf-Edhellen#33]
I was going to delete my account on the website, but apparently this involves making a "DELETE request to /api/v2/account/edit/{ID}".
I don't have the software tools or enough knowledge of HTTP to do this.

My account nickname is 'nameless' and the ID that appears in the URL is '956-tabitha_deeks'.

**Comment by galadhremmin** [comment]
Hi tabi-cat! Sorry to see you go. I've gone ahead and deleted your account now. I apologise for the inconvenience, too; the "delete account" button is something that is on my todo list.
