### ISSUE TITLE
Provide a database dump for download

### ISSUE THREAD

**Issue by b3nj5m1n** [galadhremmin/Parf-Edhellen#34]
First of all, thanks a lot for your work on this, elfdict is an awesome resource!

It would be great to have a full dump of the database behind the site available. Is there any particular reason for why this is currently not the case?

**Comment by galadhremmin** [comment]
Hi [b3nj5m1n](https://github.com/b3nj5m1n)! Thank you for your kind words.

ElfDict is open source, both the client side and the server side application, as well as the scripts and migrations that enables you to establish your own database by replaying the schema evolution. I believe that is sufficient for someone to establish their own version of the website and build an index of their own. 

ElfDict's database is the result of 11+ years of development. It is, in many ways, the heart of Parf Edhellen. There is not a single source via which you can reconstruct the glossary and the search index that are the results of years of adhoc and systematized imports. It has lots of value but it has also lots of issues; idiosyncrasies I'd like to fix before considering going open source. The interest in the project has also been perpetually low, and I'm concerned that by expanding the scope of what is considered open source, interest will continue to wane as people turn to derivative works. Or in other words, copies of Parf Edhellen would pop up without driving engagement on the main project.

For these reasons, I've decided to let the schema be public, whereas the data (in its current form) is not. However, I'd be open to provide a excerpt of the database as a seed, if you believe that'd be useful.

Thanks,
Aldaleon

**Comment by Omikhleia** [comment]
FWIW, a comment in passing: the confusion between what parts are open source (= the web site source _code_) and what isn't (= the actual database content, according to your answer above) could be clarified. Esp. when the website say...
> Welcome to the Parf Edhellen, The collaborative dictionary dedicated to Tolkien's amazing languages. (...) Parf Edhellen is open source

... It might be ambiguous to readers whether the dictionary content is an open asset (= rather "open data" than "open source" in the stricter sense, although it could be debated what "source" represents - how, e.g. a database dump would be considered). From what is said above, the database is currently "closed data", as...

> (...) interest will continue to wane as people turn to derivative works. Or in other words, copies (...) would pop up without driving engagement on the main project.

While this is understandable to some respect, I'd nevertheless hope you'd reconsider that position one day:

This is exactly how you could "quick start" the project initially (the 2012 website already mentioned it as " .. our composite, collaborative dictionary consisting of imported glosses from Hiswelókë Sindarin Dictionary, Ardalambion Quenya Wordlists and more."). It is still the case as of today (e.g. your importing Eldamo) - The dictionaries on Parf Edhellen are in large part a _derivative_ (indeed composite) _work_ based on other project (partly, with also, obviously, unrelated additions from user contributions).

Don't misunderstand me here:
  - You always acknowledged the fact, which is good practice and very well, honest and transparent (something other people easily forget!)
  - None of the above projects (I'd hope, but I can only testify for the HSD) would accuse you of having contributed to "waning interest in their own project as people turn to derivative works", wouldn't they? ^^

So there's, at least, kind of a "moral" position here in opening the data. Indeed the risk exists of a "rip off"... But there could also be interesting uses (e.g. statistics, data analysis, cross-checks...).

This is said beyond any "legal" position. I cannot judge obviously whether importing (e.g.) Parviphith is legit or not ; Eldamo is probably ok as it is licensed under CC-BY-4.0 (so even authorizing commercial use and closed versions, as long as there is attribution)... But on the other hand, heh! I _could_ note that I'm pretty sure that the HSD already was license under CC-BY-NC-SA 2.0 at the time (much earlier it once had a more restrictive license too), i.e. Non-Commercial... but also, almost all, _Share-Alike_...

**Comment by galadhremmin** [comment]
> FWIW, a comment in passing: the confusion between what parts are open source (= the web site source code) and what isn't (= the actual database content, according to your answer above) could be clarified. Esp. when the website says...

While I believe the distinction is in _open *source*_ (vs _open data_), I'd be happy to rework the text to be more explicit regarding what is and what is not available for download. Reworking the "static" texts on Parf Edhellen is on my backlog as they are, for the most part, dreadfully old and comparatively poorly written.

> While this is understandable to some respect, I'd nevertheless hope you'd reconsider that position one day:

None of the content available on Parf Edhellen today have been obtained without permission, but the permission was given for the use on the website, not for redistribution. It's been my assumption that the authors of these resources would prefer to distribute the dictionaries themselves, where Eldamo is available on Github and Hiswelókë is available for download. Ardalambion is also available via Helge's website, although the format is not structured.

> But there could also be interesting uses (e.g. statistics, data analysis, cross-checks...).

I'd be more than happy to explore such use cases! In most cases though, [Eldamo](https://github.com/pfstrack/eldamo) would probably be a better choice.

**Comment by Omikhleia** [comment]
> but the permission was given for the use on the website, not for redistribution

As of the HSD, I _certainly_ never wrote or said anything to that effect.

**Comment by galadhremmin** [comment]
I should clarify that what I meant was that I have _never asked_ whether I can redistribute the derivative datasets! I realize that the wording caused confusion. @Omikhleia in your particular case, I've responded in our other thread.

**Comment by galadhremmin** [comment]
> also, almost all, Share-Alike...

I was reading up about this and I believe I have a solution for providing a dump of the relevant datasets which have this clause in their terms. I'll just have to look a little closer into the  `mysqldump` command and its capabilities.

**Comment by galadhremmin** [comment]
First dump is available from SINDICT: https://github.com/galadhremmin/Parf-Edhellen/blob/master/model/5.%20sindict.sql
I've created a script for generating these dumps here: https://github.com/galadhremmin/Parf-Edhellen/blob/master/mysql-dump.sh

I'll work on refreshing SINDICT next so that the dump is brought up-to-date. Closing the task as this improvement will be incremental to what is already available.
